### ISSUE TITLE
OscarSocket listener should be mutable

### ISSUE THREAD

**Issue by arashpayan** [zood/george#58]
The MainFragment needs to be able to unsubscribe when it's stopped, or else you may get crashes like the following:

```
2019-10-05 20:20:54.284 26964-19383/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-185
    Process: xyz.zood.george, PID: 26964
    java.lang.IllegalStateException: Fragment MainFragment{624016d (e9a4d73c-3d17-4e05-935d-ff9392c9e7e8)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
        at xyz.zood.george.MainFragment$24.onPushNotificationReceived(MainFragment.java:1185)
        at io.pijun.george.api.OscarSocket$5.run(OscarSocket.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-10-05 20:20:54.284 26964-19385/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-188
    Process: xyz.zood.george, PID: 26964
    java.lang.IllegalStateException: Fragment MainFragment{624016d (e9a4d73c-3d17-4e05-935d-ff9392c9e7e8)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
        at xyz.zood.george.MainFragment$24.onPushNotificationReceived(MainFragment.java:1185)
        at io.pijun.george.api.OscarSocket$5.run(OscarSocket.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by arashpayan** [comment]
Fixed in v0.42
