### ISSUE TITLE
Crash:  java.lang.IllegalStateException: Fragment MainFragment not attached to a context.

### ISSUE THREAD

**Issue by arashpayan** [zood/george#59]
Stack trace:
```
2019-11-18 17:02:21.890 17338-20798/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-27
    Process: xyz.zood.george, PID: 17338
    java.lang.IllegalStateException: Fragment MainFragment{e2ba704 (8b401f5c-2fe3-4016-bcc7-8f3d5356e755)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
        at xyz.zood.george.MainFragment$24.onPackageReceived(MainFragment.java:1180)
        at io.pijun.george.api.OscarSocket$4.run(OscarSocket.java:155)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

The crash is a result of the call to `requireContext()`:
```
        @Override
        public void onPushNotificationReceived(@NonNull PushNotification notification) {
            L.i("MF.onPushNotificationReceived");
            MessageProcessor.Result result = MessageProcessor.decryptAndProcess(requireContext(),
                    notification.senderId,
                    notification.cipherText,
                    notification.nonce);
            if (result != MessageProcessor.Result.Success) {
                L.i("MF error decrypting+processing push notification: " + result);
            }

            // Was this a transient message?
            if (notification.id == null || notification.id.equals("0")) {
                return;
            }
```

**Comment by arashpayan** [comment]
`onPackageReceived` now uses the application context instead of the fragment context so this is no longer a problem.
