### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by minax007** [zood/george#78]
First I would like to thank the developer for this excellent App!

On two Android 12 devices I have realized the problem that the app crashes as soon as you click on a person whose location you want to see. Latest when you click on "Refresh" it crashes. 

I have checked the same App on an Android 10 device and it works perfectly fine.

**Comment by arashpayan** [comment]
Hi @minax007. I've been running the app on several Android 12 devices for over a year now without experiencing such crashes. Do you think you might be able to obtain the crash logs from the app? I can probably fix the bug(s) pretty quickly with the logs.

**Comment by minax007** [comment]
Hi @arashpayan 

thanks for your response!

I have no clue how to obtain the crash log. 

Recently I have figured out that the app does not crash when I move the map a little bit and then click on the person on the bottom left corner. 

If I do not do this and click on the person then in most cases the app crashes. 

Probably this issue is not even related to Android 12 as you have mentioned. I am using microG instead of Google services.

**Comment by minax007** [comment]
It seems to be related to microG. 

I have just tested the app on several devices with microG and those show the same behaviour as previously described. 

Then I have tested the app on a device with Google services and it works fine. 

On the microG devices it helps to move the map before clicking on the person on the bottom left corner. This helps but sometimes it still crashes. 

Nevertheless I love this app and highly appreciate your excellent work!

**Comment by minax007** [comment]
I have figured out a workaround how to use this app in a stable way on a system with MicroG instead of Google Services Framework:

Before you do any selection of a person or click on the refresh button you have to move the map a little bit, then lift your finger and click on the map again. 

If you then do the selection of a person or press on refresh it does not crash. 

Well this is not ideal from UX perspective ... but for me it does the job.

**Comment by billie80** [comment]
I have the same issue with microG. From the Log I get the following error:
FATAL EXCEPTION: main
Process: xyz.zood.george, PID: 27765
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
	at com.google.android.gms.dynamic.ObjectWrapper.unwrap(com.google.android.gms:play-services-basement@@18.0.0:3)
	at com.google.android.gms.maps.model.Circle.getTag(com.google.android.gms:play-services-maps@@18.0.0:1)
	at xyz.zood.george.MainFragment.updateMarker(MainFragment.java:1088)
	at xyz.zood.george.MainFragment.onFriendLocationUpdated(MainFragment.java:1243)
	at io.pijun.george.database.DB$2.run(DB.java:800)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

I hope this helps fixing the issue.

**Comment by arashpayan** [comment]
@serrq, issue #67 covers making a version of the app available that doesn't depend on Google Play Services, which would obviate the need for microG.

**Comment by guland2000** [comment]
Micro G? Can someone explaine (not about MicroG) what kind of modules microG must be installed? For that?!

**Comment by minax007** [comment]
> Micro G? Can someone explaine (not about MicroG) what kind of modules microG must be installed? For that?!

The app works without any specific modules in an operating system with microG instead of Google Play Services. 

But it is buggy.

**Comment by RasheedAZ** [comment]
> The app works without any specific modules in an operating system with microG instead of Google Play Services.

Zood has also been working for me fine on CalyxOS with microG for the past 4 years.

@arashpayan  I think this issue can be closed.

**Comment by arashpayan** [comment]
I'll close this issue now, but I just released an update that replaces Google Maps with MapLibre so the microg dependency should be even less (not at all?) relevant now.
https://github.com/zood/george/releases/tag/v0.46
